from .rmbg_cut_png import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS


def load_nodes():
    return NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "load_nodes"]
